name: Invoke Azure Function on Push

on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    needs: [main_webbyapi, main_mywebbsi]
    steps:
    - name: Invoke Azure Function
      run: curl -d "" -X POST ${{ secrets.AZSADATA }}
