name: Invoke Azure Function on Push
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Invoke Azure Function
      run: curl -d "" -X POST ${{ secrets.https://webbyapi.azurewebsites.net }}
