deploy:
  runs-on: ubuntu-latest
  needs: build
  environment:
    name: 'Production'
    url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

  steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: python-app

    - name: Unzip artifact for deployment
      run: unzip release.zip

    # Debug: List files to see the structure
    - name: List files in artifact
      run: ls -R

    # Default deployment step (try this first)
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      id: deploy-to-webapp
      with:
        app-name: 'webbysmine'
        slot-name: 'Production'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_590EA66CF1694FE4868B6294F6461D35 }}

    # Optional: Manual deployment using Kudu Zip Deploy (if the above step doesn't place files in wwwroot)
    - name: Manual Deployment using Kudu Zip Deploy
      if: failure() # Only run if the previous step failed
      run: |
        curl -X POST -u $AZURE_USERNAME:$AZURE_PASSWORD --data-binary @release.zip https://webbysmine.scm.azurewebsites.net/api/zipdeploy
      env:
        AZURE_USERNAME: ${{ secrets.AZURE_USERNAME }}
        AZURE_PASSWORD: ${{ secrets.AZURE_PASSWORD }}
